---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project-insta
  namespace: flux-system
spec:
  despendsOn:
   - name: init-infra 
  interval: 10m0s
  path: ./projects/instavote-app/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

